package com.swd392.mentorbooking.entity.Enum;

public enum SpecializationEnum {
    SCIENCE,
    ARTS,
    ENGINEERING,
    BUSINESS,
    IMAGE_PROCESSING,
    API_DEVELOPMENT,
    NETWORK,
    DATABASE,
    TESTING,
    EMBEDDED,
    AI,
    MOBILE_DEVELOPMENT,
    FRONTEND_WEB_DEVELOPMENT,
    BACKEND_WEB_DEVELOPMENT,
    FULLSTACK_WEB_DEVELOPMENT,
    SOFTWARE_DEVELOPMENT,
    DOCUMENTATION
}
